### PR TITLE
Use version argument from docopt instead

### PR DESCRIPTION
**Pull request by titipata**
This should be a little cleaner than the former one.

### CODE REVIEW

**Comment by heytitle** [comment]
@titipata Thanks for the PR!

**Comment by titipata** [comment]
no problem @heytitle!

**Comment by titipata** [comment]
BTW, @heytitle, I forgot to change `README` to the current updated `attacut-cli`

**Comment by heytitle** [comment]
@titipata thanks for the reminding. I've updated `README` accordingly and also published the change. You can now use it with `attacut==1.0.6`.

**Comment by titipata** [comment]
Sounds great! Thanks!

**Pull request merged**
