### PR TITLE
Fix tokenize error for empty string input

### PR DESCRIPTION
**Pull request by pamin2222**
Problem:
```
import attacut
attacut.tokenize("")

# ... RuntimeError: Calculated padded input size per channel: (2). Kernel size: (3). Kernel size can't be greater than actual input size
```

### CODE REVIEW

**Comment by bact** [comment]
Should we return `[""]` or `[]` ?

**Comment by pamin2222** [comment]
Oh, I just noticed that you did handle this case in PyThaiNLP by returning `[]` already.

I think `[]` is okay because NLTK, Spacy, and Jieba are also return nothing for an empty string input.

Thank you.

**Comment by heytitle** [comment]
@pamin2222, @bact.
Thank you very much for the fix.  I've just released it in v.1.0.5.

**Comment by bact** [comment]
> I think `[]` is okay because NLTK, Spacy, and Jieba are also return nothing for an empty string input.

Current attacut now returns `[""]` (an array of one empty string) if input is `""` (empty string).

Should we keep it like this, or should we make is consistent with other library - by returning `[]` (an array of nothing)?

**Pull request merged**
