### PR TITLE
List model in artifacts

### PR DESCRIPTION
**Pull request by wannaphong**
I edited `__init__.py` in artifacts. It can list model in artifacts.

### CODE REVIEW

**Comment by heytitle** [comment]
hi, thanks for the PR. 

Would you mind elaborating a bit why we need this?

**Comment by wannaphong** [comment]
This will facilitate those who fork this project and want to use trained model through attacut.

**Comment by heytitle** [comment]
The names `attacut-c and -sc` are just aliases. 
Can you try to specify the path manually e.g. `attack("./artifacts/...")`?

**Comment by wannaphong** [comment]
> 
> 
> The names `attacut-c and -sc` are just aliases.
> Can you try to specify the path manually e.g. `Tokenizer(model="./artifacts/...")`?

I think it's not easy when the model is different folder.

**Comment by heytitle** [comment]
> The names attacut-c and -sc are just aliases.
Can you try to specify the path manually e.g. Tokenizer(model="./artifacts/...")?
I think it's not easy when the model is different folder.

How about using the path to that directory (either relative or absolute)?  For example,
```
Tokenizer(model="<my-other-project-dir>/models/...")
```

**Comment by heytitle** [comment]
I think I'll close this. feel free to reopen it if you see there is still an issue.

**Pull request closed without merging**
